# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# site wide defaults
# Site settings
title: Shuigui's Blog
email: hsguidemail@gmail.com

author: Shuigui

description: >
  A personal tech blog sharing learning notes on deep learning, machine learning,
  C++, and web development. Plus useful developer tools.
baseurl: # the subpath of your site, e.g. /blog
url: "https://hsgui.github.io" # the base hostname & protocol for your site
twitter_username: HShuigui
github_username:  hsgui

# SEO
lang: en

# Build settings
markdown: kramdown
